Eswar insq1q2 242
sf-industries/q1q2_ins_qe_rafi_test pull request #2
Opened 2022-11-10 10:27 UTC by aaddepalli

First review

2022-11-11 11:04 UTC, lavanya948 approved these changes

2022-11-11 11:04 UTC, lavanya948 commented on pom.xml
> +    <artifactId>RAFI-Core-SampleTestProject</artifactId>
Is it intentional to keep SampleTestProject for group & artifactId?

2022-11-11 11:08 UTC, aaddepalli commented on pom.xml
> +    <artifactId>RAFI-Core-SampleTestProject</artifactId>
No.. I changed it

2022-11-11 11:11 UTC, lavanya948 approved these changes

2022-11-11 11:31 UTC, lavanya948 approved these changes

2022-11-15 09:41 UTC, lavanya948 requested changes

2022-11-15 09:41 UTC, lavanya948 commented on src/test/resources/setup/users-setup_default.json
> +{
This file is not required for insurance as the credentials are not related to insurance org

2022-11-15 09:41 UTC, lavanya948 commented on src/test/resources/setup/users-setup_GS0.json
> +    {
Please update user credentials with Q2 org user details

2022-11-15 09:41 UTC, lavanya948 commented on src/test/resources/setup/configuration.properties
> +#
Not required for insurance tests

2022-11-15 10:12 UTC, aaddepalli commented on src/test/resources/setup/configuration.properties
> +#
Removed.

2022-11-15 10:12 UTC, aaddepalli commented on src/test/resources/setup/users-setup_GS0.json
> +    {
Fixed.

2022-11-15 10:12 UTC, aaddepalli commented on src/test/resources/setup/users-setup_default.json
> +{
Updated.

2022-11-15 10:14 UTC, lavanya948 approved these changes

2022-11-15 10:18 UTC, ankit-sharma-3 approved these changes

2022-11-15 10:18 UTC, merged